#!/bin/bash

kill_registry() {
  echo "killing registry..."
  sv down go-docker-registry
  rm /etc/service/go-docker-registry
  i=0
  while [ "$(pidof registry)" ] && [ $i -lt 5 ]; do
    echo "waiting for registry to die..."
    sleep 1
    (( i++ ))
  done
  if [ "$(pidof registry)" ]; then
    echo "registry is proving resilient. bringing out the big guns..."
    kill -9 $(pidof registry)
  fi
  echo "registry killed."
}

if [ -L '/etc/service/go-docker-registry' ]; then
  kill_registry
fi

mkdir -p /var/log/atlantis/registry
